/* #undef SDL2COMPAT_VENDOR_INFO */
#define SDL_REVISION_NUMBER 0

#ifdef SDL2COMPAT_VENDOR_INFO
#define SDL_REVISION "SDL-2.32.59-gb5bd4c5 (" SDL2COMPAT_VENDOR_INFO ")"
#else
#define SDL_REVISION "SDL-2.32.59-gb5bd4c5"
#endif
